version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: questar-client
    volumes:
      - ./client/app:/usr/src/app
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: questar-server
    volumes:
      - ./server/src:/go/src
    command: air
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: questar-db
    ports:
      - "5332:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: questar
      POSTGRES_PASSWORD: admin
    restart: always
